services:
  # CLÚSTER A: Cómputo Oficial (Consistencia Fuerte)
  db_oficial:
    image: postgres:16-alpine
    container_name: db_oficial
    environment:
      - POSTGRES_USER=antigravity
      - POSTGRES_PASSWORD=bolivia_vota
      - POSTGRES_DB=electoral_db
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Carga automática de las 4 hojas
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U antigravity -d electoral_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # CLÚSTER B: Recuento Rápido / RRV (Baja Latencia)
  db_rapido:
    image: postgres:16-alpine
    container_name: db_rapido
    environment:
      - POSTGRES_USER=antigravity
      - POSTGRES_PASSWORD=bolivia_vota
      - POSTGRES_DB=rrv_db
    ports:
      - "5434:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U antigravity -d rrv_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis_queue:
    image: redis:7-alpine
    container_name: redis_queue

  backend-api:
    build: ../backend
    container_name: backend_api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db_oficial
      - DB_REPLICA_HOST=db_rapido
      - DB_USER=antigravity
      - DB_PASS=bolivia_vota
      - DB_NAME=electoral_db
      - DB_NAME_RRV=rrv_db
    depends_on:
      db_oficial:
        condition: service_healthy
      redis_queue:
        condition: service_started
    volumes:
      - ../backend:/app
      - ../data/ingest:/app/ingest

  frontend-svelte:
    image: node:20-alpine
    container_name: frontend_svelte
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
